settings:
  paths:
    backend_1:
      backend_mounted: false
      backend_cache_root: /backend
    staging:
      staging_mounted: true
      staging_mount_root: /staging

webdav:
  games:
    backend_folder: /games
    frontend_folder: /games
    users:
      tester:
        login: true
        read: true
        write: false
        cache: false
